# Generated by Django 3.0.8 on 2020-07-26 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        ('accounthistory', '0002_accounthistory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfers.Transfer'),
        ),
    ]
