# Generated by Django 3.0.8 on 2020-07-26 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounthistory', '0003_accounthistory_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
